# 
#       NOTE:
# Instances of "[[hidden]]" are hiding sensitive strings of code/data in this instance only; respective code remains in tact in the production YAML file.
# 

# Production YAML starts here:
esphome:
  name: esphome-web-024a8c
  friendly_name: wemos-esp-car_automation

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "[[hidden]]"

ota:


wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  - ssid: uber_brandon
    password: [[hidden]]

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-024A8C"
    password: "[[hidden]]"

#                   RST | TX GPIO1 <
#                    A0 | RX GPIO3 <
#             GPIO16 D0 | D1 GPIO5 < Main
# WindowSw  > GPIO14 D5 | D2 GPIO4 < FlasherSn
# FlasherSw > GPIO12 D6 | D3 GPIO0 < DomeLtSn
# DomeLtSw  > GPIO13 D7 | D4 GPIO2
#             GPIO15 D8 | G
#                   3V3 | 5V

captive_portal:

http_request:
  useragent: esphome/device
  timeout: 10s

binary_sensor:

##################### binary_sensor

  - platform: gpio
    name: "Master Switch"
    device_class: connectivity
    id: master_switch
    pin:
      number: GPIO5 #D1
      mode: INPUT_PULLUP
      inverted: true
    on_press:
       then:
         - switch.turn_on: flashers_relay
         - switch.turn_on: dome_relay
    on_release:
       then:
         - switch.turn_off: flashers_relay
         - switch.turn_off: dome_relay

##################### binary_sensor

  - platform: gpio
    name: "Flashers Soft"
    device_class: connectivity
    id: flashers_soft
    pin:
      number: GPIO4 #D2
      mode: INPUT_PULLUP
      inverted: true
    on_press:
       then:
         - switch.toggle: flashers_relay
    on_release:
       then:
         - switch.toggle: flashers_relay

##################### binary_sensor

  - platform: gpio
    name: "Window Button"
    device_class: connectivity
    id: window_button
    pin:
      number: GPIO3 #RX
      mode: INPUT_PULLUP
      inverted: true
    on_press:
       then:
         - http_request.get: 
             url: https://trigger.macrodroid.com/[[hidden]]/UberSwipe
             verify_ssl: false
         - delay: 1s
         - http_request.get: 
             url: https://trigger.macrodroid.com/[[hidden]]/Uber2
             verify_ssl: false
         - delay: 1s
         - http_request.get: 
             url: https://trigger.macrodroid.com/[[hidden]]/Uber3
             verify_ssl: false

switch:

##################### switch

  - platform: gpio
    pin: GPIO12 #D6
    name: "Flashers Relay"
    id: flashers_relay

##################### switch

  - platform: gpio
    pin: GPIO13 #D7
    name: "Dome Relay"
    id: dome_relay
